Many bug fixes.
Iterating toward more stable user/system configuration


Former-commit-id: 98777a182c4aa4fc2ce4b0d241741063c2e2c77d [formerly 3649644c296904fae89da94c83da4401b76395f0] [formerly d3c766811869b31332bfdbde17336dd9355a0406]
Former-commit-id: 13d60c1fe1d4f7c6ebfdffe1df2241015742d9ce
Former-commit-id: 73173266aa041b6672b3865186087f65ed3b58bb

diff --git a/bin/tau b/bin/tau
--- a/bin/tau
+++ b/bin/tau
@@ -39,7 +39,6 @@
 ################################################################################
 TAU_HOME="$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )"
 SRC="tau"
-#BUILD="build"
 
 # Go to the script directory
 cd "$TAU_HOME"
@@ -50,6 +49,12 @@ cd "$TAU_HOME"
 # Add TAU top level directory to PYTHONPATH
 export TAU_MASTER_SRC_DIR="$TAU_HOME/$SRC"
 export PYTHONPATH=$TAU_MASTER_SRC_DIR:$PYTHONPATH
+
+# Check python
+if ! which python >/dev/null 2>&1 ; then
+  echo "ERROR: 'python' not found in PATH"
+  exit 1
+fi
 
 # Invoke TAU Commander
 python $TAU_MASTER_SRC_DIR/taucmd/__main__.py "$@"
