Update TAU source to 2.24
commit 66a779d953f4f61ca65e40d3c51b4743c3d33222


Former-commit-id: 2a5f4f11ae9302dd8c19b4b9e41ddcacfa4aa960 [formerly ee7325df8341dcb128d0e7fa2f4dc7fa93bd3119] [formerly 09301a2a98e91ec9db508ed1bd127b0eebd9b974]
Former-commit-id: b32d375385ce32a88535ca5bb5a667a35bbb305a
Former-commit-id: 73ea8f88dce622e5f0fc7de87767af69440125b9

diff --git a/tau/utils/FixMakefile b/tau/utils/FixMakefile
--- a/tau/utils/FixMakefile
+++ b/tau/utils/FixMakefile
@@ -122,7 +122,7 @@ case $1 in
 
      unwind_lib_flag=*)
         unwind_lib_flag=`echo $1 | sed -e 's/^unwind_lib_flag=//' -e 's/#/ /g'`
-       echo "s,^UNWIND_LIB_FLAG=.*$,UNWIND_LIB_FLAG=$unwind_lib_flag,g" >> $sedout
+        echo "s@^UNWIND_LIB_FLAG=\(.*\)@UNWIND_LIB_FLAG=$unwind_lib_flag@g" >> $sedout
         ;;
 
      unwind_extras=*)
@@ -399,6 +399,18 @@ case $1 in
 	echo "s@^TAU_BUILD_CXX=.*@TAU_BUILD_CXX=$tau_build_cxx@g" >> $sedout
 	;;
 
+     boostdir=*)
+        boostdir=`echo $1 | sed -e 's/^boostdir=//'`
+	echo "s,^BOOSTDIR=.*$,BOOSTDIR=$boostdir,g" >> $sedout
+	;;
+     boostinc=*)
+        boostinc=`echo $1 | sed -e 's/^boostinc=//'`
+	echo "s,^TAU_BOOSTINC=.*$,TAU_BOOSTINC=$boostinc,g" >> $sedout
+	;;
+     boostlib=*)
+        boostlib=`echo $1 | sed -e 's/^boostlib=//'`
+	echo "s,^TAU_BOOSTLIB=.*$,TAU_BOOSTLIB=$boostlib,g" >> $sedout
+	;;
      dyninstdir=*)
         dyninstdir=`echo $1 | sed -e 's/^dyninstdir=//'`
 	echo "s,^DYNINSTDIR=.*$,DYNINSTDIR=$dyninstdir,g" >> $sedout
@@ -429,6 +441,16 @@ case $1 in
 	echo "s,^ANDROID_SDK=.*$,ANDROID_SDK=$android_sdk,g" >> $sedout
 	;;
 
+     android_version=*)
+        android_version=`echo $1 | sed -e 's/^android_version=//'`
+	echo "s,^ANDROID_VERSION=.*$,ANDROID_VERSION=$android_version,g" >> $sedout
+	;;
+
+     android_platform=*)
+        android_platform=`echo $1 | sed -e 's/^android_platform=//'`
+	echo "s,^ANDROID_PLATFORM=.*$,ANDROID_PLATFORM=$android_platform,g" >> $sedout
+	;;
+
      pythoninc=*)
         pythoninc=`echo $1 | sed -e 's/^pythoninc=//'`
 	echo "s,^PYTHON_INCDIR=.*$,PYTHON_INCDIR=$pythoninc,g" >> $sedout
@@ -438,7 +460,14 @@ case $1 in
      pythonlib=*)
         pythonlib=`echo $1 | sed -e 's/^pythonlib=//'`
 	# Discover python library version
-	pythonso=`ls $pythonlib/libpython*.so | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.so//'`
+	pythonso=`ls $pythonlib/libpython*.so 2>/dev/null | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.so//'`
+	if [ "x$pythonso" = "x" ] ; then
+	  pythonso=`ls $pythonlib/libpython*.dylib 2>/dev/null | head -1 | xargs basename | sed -e 's/lib//' -e 's/\.dylib//'`
+	  if [ "x$pythonso" = "x" ] ; then
+	    echo "ERROR: Cannot find python library (libpython*.[so|dylib]"
+	    exit 1
+	  fi
+	fi
 	echo "s,^PYTHON_LIBDIR=.*$,PYTHON_LIBDIR=$pythonlib,g" >> $sedout
 	echo "s,^PYTHON_LIB_SO=.*$,PYTHON_LIB_SO=$pythonso,g" >> $sedout
 	#echo "Using PYTHON LIB DIR =" $pythonlib
@@ -576,6 +605,11 @@ case $1 in
      TAU_PERFSUITE)
         echo NOTE: Using PerfSuite support
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
+        ;;
+
+     TAU_SS_ALLOC_SUPPORT)
+	echo NOTE: Compiler supports Sampling Allocator
+	echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
         ;;
 
      TAU_LINKS_RT)
@@ -733,6 +767,10 @@ case $1 in
         #echo "TAU_MPILIB_DIR=$mpilibdir" 
         ;;
 
+     TAUENV)
+        echo NOTE: Building the tau_env tool
+        echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
+        ;;
 ###############################################################
 # Set up SHMEM stuff if possible
 ###############################################################
@@ -801,6 +839,10 @@ case $1 in
         echo "NOTE: Using the TAU's CUPTI Profiling Interface "
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
         ;;
+     CUPTI_NOCUDA)
+        echo "NOTE: Couldn't locate /usr/lib/libcuda.so. Is it somewhere else? "
+        echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
+        ;;
      CUPTI_ACTIVITY)
         echo "NOTE: Using the TAU's CUPTI Activity API "
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
@@ -843,13 +885,25 @@ case $1 in
 	echo "s/^CROSS_PREFIX=\(.*\)/CROSS_PREFIX=${config_host}-/g" >> $sedout
 	;;
 
+     host_sysroot=*)
+        host_sysroot=`echo $1 | sed 's/^host_sysroot=//'`
+        echo "s/#HOST_SYSROOT#\(.*\)/$bs\1#HOST_SYSROOT#/g" >> $sedout
+	echo "s@^HOST_SYSROOT=\(.*\)@HOST_SYSROOT=${host_sysroot}@g" >> $sedout
+	;;
+
+     confenvfile=*)
+        confenvfile=`echo $1 | sed -e 's/^confenvfile=//' `
+	echo "NOTE: Saving configuration environment to $confenvfile"
+	echo "s@^CONF_ENV_FILE=\(.*\)@CONF_ENV_FILE=$confenvfile@g" >> $sedout
+        ;;
+
      HOSTUTILS)
 	echo "NOTE: Building TAU utils for HOST (i.e. cross compile)"
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
 	;;
 
      ANDROID)
-	echo NOTE: Building TAU for Android
+	echo "NOTE: Building TAU for Android $android_version, platform $android_platform"
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
 	;;
 
@@ -1126,6 +1180,10 @@ case $1 in
 	;;
      APPLECXX)
 	echo NOTE: Apple c++ compiler will be used
+        echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
+	;;
+     NOFORTRAN)
+	echo "NOTE: TAU's Fortran library bindings will not be compiled. "
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
 	;;
      APPLEPGI)
@@ -1565,6 +1623,10 @@ case $1 in
 	;;
      PAPIPTHREAD)
 	echo "NOTE: Using multi-threaded access to H/W Performance Counters ***"
+        echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
+	;;
+     PAPI_PERF_RAPL)
+	echo "NOTE: Enabling power measurements using PAPI's Perf RAPL interface ***"
         echo "s/#$1#\(.*\)/$bs\1#$1#/g" >> $sedout
 	;;
      ANSIC)
